### ISSUE TITLE
UTF-8 problems

### ISSUE THREAD

**Issue by OlleRatu** [erijo/tellcore-py#5]
When using tellcore_tool and the the device name contains utf-8 I get the following error in Python 2.7.6.

Traceback (most recent call last):
  File "/usr/local/bin/tellcore_tool", line 129, in <module>
    print_devices(core.devices())
  File "/usr/local/bin/tellcore_tool", line 47, in print_devices
    device.protocol, device.model, params_str))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 1: ordinal not in range(128)

In python3 it works fine as it defaults to unicode str's.

**Comment by erijo** [comment]
Fix included in version 1.1.2 released just now.

**Comment by OlleRatu** [comment]
Tack.
